# Generated by Django 4.2.3 on 2023-07-26 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b62d8f27-8af0-40a0-a0dc-cba9c754f171'), editable=False, primary_key=True, serialize=False),
        ),
    ]
